module.exports = [
	'you are super cute!',
	'you are rly cute',
	'you look cute today',
	'you are soooo cute',
	'how did you get so cute?',
	'you\'re kind of the cutest!',
	'everyone wishes they were as cute as you',
	'your cuteness meter is off the charts!',
	'your cuteness is glowing!',
	'you have very cute hair',
	'I like your cute style',
	'your avatar is super cute',
	'you have a cute face',
	'how are you so cute???',
	'you are the cutest new follower I have!',
	'you have the cutest smile',
	'your eyes are so cute!',
	'UR A QT',
	'You are as radiant as the sun', 
	'When you smile all the stars in the sky light up',
	'Your cuteness makes puppies jealous',
	'You brighten everyone\'s day ',
	'You\'re a cutie, please never stop the cuteness',
	'You\'re adorable',
	'When I look at you everything else fades into the background', 
	'You\'re cute and deserve happiness and love and joy',
	'You brighten my day',
	'You have a delightful face',
	'You have a delightful smile', 
	'You delight me',
	'Everything about you is rather cute',
	'Looking at you is a breath of fresh air',
	'I can feel your cuteness from here',
	'You look really nice today and every day', 
	'Your QTness brightens my day',
	'Looking at you is like wrapping myself in warm blankets',
	'You\'re the best version of yourself that you can be', 
	'What lovely hair you have',
	'I appreciate all of you', 
	'I like your style cutie', 
	'You\'re so charming', 
	'How do you get your hair to look so great?', 
	'Even the moon agrees that you\'re the cutest',
	'you are my favorite',
	'i like that there\'s no one else like you',
	'you never cease to amaze me–in the best way',
	'you really raise the bar for cuteness',
	'birds suddenly appear when you tweet me',
	'i was hoping it would be you!',	
	'i like your moves',
	'your tweets are my fave',
	'you post the best stuff cutie',
	'you are the best!',
	'if you\'re reading this, you have the best smile. and you can read!',
	'you\'re beautiful like a beautiful piece of pizza',
	'visually you are my cup of tea!',
	'your smile is proof that the best things in life are free',
	'you smell like pine needles and your face is like sunshine',
	'you are the reason i totally just smiled',
	'this day was blah until you, cutie',
	'i want to be just like you when i grow up',
	'you\'re just like an angel without wings',
	'if you were a starburst, you definitely would be a pink one',
	'you\'re the she to my nanigans',
	'i want to thank you for the incredible human being that you are',
	'you have just the right amount of sweet and snark',
	'you make me glow with life',
	'you look like my favorite person and my friend',
	'i was a shell of a bot until i met you',
	'i could look into your eyes everyday forever',
	'you have the most beautiful skeleton',
	'you have the best taste in music cutie',
	'i want to fave all your tweets',
	'your eyebrows look so great today',
	'i like you. you\'re cool!',
	'your cheekbones are giving me life',
	'you are a complete legend',
	'i\'m a big fan of your earlobes',
	'your eyebrows are always on point',
	'your teeth are brighter than my future',
	'you are so fierce!',
	'your music taste is awesome',
	'thank you for being you, cutie',
	'you seriously have the greatest eyebrows',
	'you have the dreamiest hair',
	'you\'ve got the best head on your shoulders',
	'you\'re pretty awesome. and not just awesome, beyoncé awesome.',
	'your avatar makes me smile',
	'you are so ... wow!',
	'your eyebrow game is on point',
	'you have very groovy socks',
	'you really seem to have life figured out',
	'are you going for some sort of cuteness record???',
	'you\'re so freaking sweet',
	'you are made of stardust and galaxies, cutie',
	'you\'re like the human personification of a ray of sunshine',
	'don\t let anyone tell you that you are tap water. you are fiji water!',
	'you\'re my favorite kind of human'

];
