module.exports = [
	'you are super cute!',
	'you are rly cute',
	'you look cute today',
	'you are soooo cute',
	'how did you get so cute?',
	'you\'re kind of the cutest!',
	'everyone wishes they were as cute as you',
	'your cuteness meter is off the charts!',
	'your cuteness is glowing!',
	'you have very cute hair',
	'I like your cute style',
	'your avatar is super cute',
	'you have a cute face',
	'how are you so cute???',
	'you are the cutest new follower I have!',
	'you have the cutest smile',
	'your eyes are so cute!',
	'UR A QT',
	'You are as radiant as the sun', 
	'When you smile all the stars in the sky light up',
	'Your cuteness makes puppies jealous',
	'You brighten everyone\'s day ',
	'You\'re a cutie, please never stop the cuteness',
	'You\'re adorable',
	'When I look at you everything else fades into the background', 
	'You\'re cute and deserve happiness and love and joy',
	'You brighten my day',
	'You have a delightful face',
	'You have a delightful smile', 
	'You delight me',
	'Everything about you is rather cute',
	'Looking at you is a breath of fresh air',
	'I can feel your cuteness from here',
	'You look really nice today and every day', 
	'Your QTness brightens my day',
	'Looking at you is like wrapping myself in warm blankets',
	'You\'re the best version of yourself that you can be', 
	'What lovely hair you have',
	'I appreciate all of you', 
	'I like your style cutie', 
	'You\'re so charming', 
	'How do you get your hair to look so great?', 
	'Even the moon agrees that you\'re the cutest'
];
